"""Cambio en fechas producciones

Revision ID: 02509c1f7be4
Revises: 66f0d2929165
Create Date: 2026-04-03 16:52:46.377819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02509c1f7be4'
down_revision = '66f0d2929165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_solicitud', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_completada', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('fecha_completada')
        batch_op.drop_column('fecha_solicitud')

    # ### end Alembic commands ###
