"""Solucion de errores con nombres en detalles

Revision ID: 09abbd2d87bb
Revises: f7cb974122af
Create Date: 2026-03-29 22:04:24.717369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09abbd2d87bb'
down_revision = 'f7cb974122af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('total')

    # ### end Alembic commands ###
