"""initial

Revision ID: 20d939dfcd43
Revises: 
Create Date: 2026-04-07 23:32:43.313212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20d939dfcd43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_produccion')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id_solicitud', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('solicitudes_ibfk_1')),
    sa.PrimaryKeyConstraint('id_solicitud'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('solicitudes_produccion',
    sa.Column('id_solicitud', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('solicitudes_produccion_ibfk_1')),
    sa.PrimaryKeyConstraint('id_solicitud'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
