"""PedidoMeta

Revision ID: 3d17408121ec
Revises: c9d692e4cee4
Create Date: 2026-04-08 11:04:43.268269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d17408121ec'
down_revision = 'c9d692e4cee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarjeta_titular', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tarjeta_ultimos4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('tarjeta_vencimiento', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_meta', schema=None) as batch_op:
        batch_op.drop_column('tarjeta_vencimiento')
        batch_op.drop_column('tarjeta_ultimos4')
        batch_op.drop_column('tarjeta_titular')

    # ### end Alembic commands ###
