"""Campo total en pedidos agregado

Revision ID: 66f0d2929165
Revises: 78bc5a344f7c
Create Date: 2026-04-03 03:47:55.440391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f0d2929165'
down_revision = '78bc5a344f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
