"""Cambio check imagen

Revision ID: 78bc5a344f7c
Revises: a1425a523405
Create Date: 2026-04-03 00:34:55.706161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78bc5a344f7c'
down_revision = 'a1425a523405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
