"""Actualizacion de estado persona/proveedor

Revision ID: a1425a523405
Revises: b7c6c2b3905c
Create Date: 2026-04-02 12:18:35.632513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1425a523405'
down_revision = 'b7c6c2b3905c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
