"""Arreglo de relaciones

Revision ID: c759e760c46a
Revises: 09abbd2d87bb
Create Date: 2026-03-29 22:13:28.717160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c759e760c46a'
down_revision = '09abbd2d87bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_primas',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('porcentaje_merma', sa.Float(), nullable=False),
    sa.Column('factor_conversion', sa.Float(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.CheckConstraint("unidad_medida IN ('kg', 'g', 'l', 'ml', 'pz')", name='check_unidad_medida_materia'),
    sa.CheckConstraint('factor_conversion > 0', name='check_factor_conversion_positivo'),
    sa.CheckConstraint('porcentaje_merma >= 0 AND porcentaje_merma <= 100', name='check_porcentaje_merma'),
    sa.CheckConstraint('precio >= 0', name='check_precio_materia_no_negativo'),
    sa.CheckConstraint('stock_actual >= 0', name='check_stock_actual_materia_no_negativo'),
    sa.CheckConstraint('stock_minimo >= 0', name='check_stock_minimo_materia_no_negativo'),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_materia'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producciones',
    sa.Column('id_produccion', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('Solicitada', 'En Proceso', 'Completada')", name='check_estado_produccion'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_produccion')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint("metodo_pago IN ('Efectivo', 'Tarjeta', 'Transferencia')", name='check_metodo_pago_venta'),
    sa.CheckConstraint('total >= 0', name='check_total_venta_no_negativo'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('carritos',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    op.create_table('detalle_compra',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_u', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_cantidad_positiva'),
    sa.CheckConstraint('precio_u >= 0', name='check_precio_u_no_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='check_subtotal_no_negativo'),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('detalle_produccion',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('id_produccion', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.ForeignKeyConstraint(['id_produccion'], ['producciones.id_produccion'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_cantidad_venta_positiva'),
    sa.CheckConstraint('subtotal >= 0', name='check_subtotal_venta_no_negativo'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('movimientos_caja',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_caja', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('Ingreso', 'Egreso')", name='check_tipo_movimiento'),
    sa.CheckConstraint('monto >= 0', name='check_monto_movimiento_no_negativo'),
    sa.ForeignKeyConstraint(['id_caja'], ['caja.id_caja'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('receta_detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias_primas.id_materia'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('detalle_carrito',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_cantidad_carrito_positiva'),
    sa.CheckConstraint('subtotal >= 0', name='check_subtotal_carrito_no_negativo'),
    sa.ForeignKeyConstraint(['id_carrito'], ['carritos.id_carrito'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_carrito')
    op.drop_table('receta_detalle')
    op.drop_table('movimientos_caja')
    op.drop_table('detalle_venta')
    op.drop_table('detalle_produccion')
    op.drop_table('detalle_compra')
    op.drop_table('carritos')
    op.drop_table('ventas')
    op.drop_table('recetas')
    op.drop_table('producciones')
    op.drop_table('materias_primas')
    # ### end Alembic commands ###
