"""init

Revision ID: c9d692e4cee4
Revises: 
Create Date: 2026-04-08 07:37:29.285517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d692e4cee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pedido', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id_pedido'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_pedido')

    # ### end Alembic commands ###
