"""Materia nulleable)

Revision ID: d503e73bb69d
Revises: 02509c1f7be4
Create Date: 2026-04-03 23:42:03.380802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd503e73bb69d'
down_revision = '02509c1f7be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_produccion', schema=None) as batch_op:
        batch_op.alter_column('id_materia',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_produccion', schema=None) as batch_op:
        batch_op.alter_column('id_materia',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
